all:
	$(MAKE) -C ex00
	$(MAKE) -C ex01
	$(MAKE) -C ex02
	$(MAKE) -C ex03
	$(MAKE) -C ex04


ex00:
	$(MAKE) -C ex00
ex01:
	$(MAKE) -C ex01
ex02:
	$(MAKE) -C ex02
ex03:
	$(MAKE) -C ex03

clean:
	$(MAKE) -C ex00 fclean
	$(MAKE) -C ex01 fclean
	$(MAKE) -C ex02 fclean
	$(MAKE) -C ex03 fclean

.PHONY : ex00 ex01 ex02 ex03