all:
	$(MAKE) -C ex00
	$(MAKE) -C ex01
	$(MAKE) -C ex02
	$(MAKE) -C ex03
	$(MAKE) -C ex04
	$(MAKE) -C ex05
	$(MAKE) -C ex06


ex00:
	$(MAKE) -C ex00
ex01:
	$(MAKE) -C ex01
ex02:
	$(MAKE) -C ex02
ex03:
	$(MAKE) -C ex03
ex04:
	$(MAKE) -C ex04
ex05:
	$(MAKE) -C ex05
ex06:
	$(MAKE) -C ex06

clean:
	$(MAKE) -C ex00 fclean
	$(MAKE) -C ex01 fclean
	$(MAKE) -C ex02 fclean
	$(MAKE) -C ex03 fclean
	$(MAKE) -C ex04 fclean
	$(MAKE) -C ex05 fclean
	$(MAKE) -C ex06 fclean

.PHONY : ex00 ex01 ex02 ex03 ex04 ex05 ex06